- ansible.builtin.import_role:
    name: compose_hull
    tasks_from: facts
  vars:
    service_defaults:
      directory: "{{ docker_dir }}/traefik"
      name: traefik
      domain: "traefik.example.com"
      port: 9000
      traefik: false
      external: true
      watchtower: true
      autoheal: true
      internal_ip_ranges: []
      cockpit:
        enabled: false
        domain: "cockpit.example.com"
      authelia:
        enabled: false
        domain: "auth.example.com"
      skip_network_definition: true
      subdirs: []

- ansible.builtin.import_role:
    name: compose_hull
    tasks_from: create_directories

- name: Copy static config traefik.yml
  template:
    src: traefik.yml.j2
    dest: '{{ service_dir }}/traefik.yml'
    owner: '{{ admin.name }}'
    group: 'docker'
  tags: [ started, restarted, recreated ]

- name: Copy dynamic config files
  copy:
    src: "{{ item }}"
    dest: '{{ service_dir }}/rules/{{ item }}'
    owner: '{{ admin.name }}'
    group: 'docker'
  tags: [ started, restarted, recreated ]
  with_items:
    - tls-options.yml
    - https-redirect-all.yml

- name: Copy rules/app-cockpit.yml
  template:
    src: app-cockpit.yml.j2
    dest: '{{ service_dir }}/rules/app-cockpit.yml'
    owner: '{{ admin.name }}'
    group: 'docker'
  tags: [ started, restarted, recreated ]

- name: Copy rules/middlewares.yml
  template:
    src: middlewares.yml.j2
    dest: '{{ service_dir }}/rules/middlewares.yml'
    owner: '{{ admin.name }}'
    group: 'docker'
  tags: [ started, restarted, recreated ]

- name: ensure acme.json exists
  copy:
    content: ""
    dest: '{{ service_dir }}/acme.json'
    force: no
    group: docker
    owner: "{{ admin.name }}"
    mode: 0600
  tags: [ started, restarted, recreated ]

- ansible.builtin.import_role:
    name: compose_hull
    tasks_from: deploy_docker
