- ansible.builtin.import_role:
    name: compose_hull
    tasks_from: facts
  vars:
    service_defaults:
      directory: "{{ docker_dir }}/traefik"
      name: traefik
      domain: "traefik.example.com"
      port: 8080
      traefik: true
      external: true
      watchtower: true
      autoheal: true
      internal_ip_ranges: []
      skip_network_definition: false
      subdirs:
        - "dynamic"

- name: "Get User ID"
  command: "sh -c 'getent passwd {{ admin.name }} | cut -d: -f3'"
  register: command_output
  tags: [ always, started, restarted, recreated ]

- name: "Store User ID: {{ command_output.stdout }}"
  set_fact: PUID=command_output.stdout
  tags: [ always, started, restarted, recreated ]

- name: "Get Goup ID of docker"
  command: "sh -c 'getent group docker | cut -d: -f3'"
  register: command_output
  tags: [ always, started, restarted, recreated ]

- name: "Store Goup ID of docker: {{ command_output.stdout }}"
  set_fact: PGID=command_output.stdout
  tags: [ always, started, restarted, recreated ]

- ansible.builtin.import_role:
    name: compose_hull
    tasks_from: create_directories

- name: Copy static config traefik.yml
  template:
    src: traefik.yml.j2
    dest: '{{ service_cfg.directory }}/traefik.yml'
    owner: '{{ admin.name }}'
    group: 'docker'
  tags: [ always, started, restarted, recreated ]

- name: Copy dynamic config files
  copy:
    src: "{{ item }}"
    dest: '{{ service_cfg.directory }}/dynamic/{{ item }}'
    owner: '{{ admin.name }}'
    group: 'docker'
  tags: [ always, started, restarted, recreated ]
  with_items:
    - tls-options.yml
    - https-redirect-all.yml

- name: Copy rules/middlewares.yml
  template:
    src: middlewares.yml.j2
    dest: '{{ service_cfg.directory }}/dynamic/middlewares.yml'
    owner: '{{ admin.name }}'
    group: 'docker'
  tags: [ always, started, restarted, recreated ]

- name: ensure acme.json exists
  copy:
    content: ""
    dest: '{{ service_cfg.directory }}/acme.json'
    force: no
    group: docker
    owner: "{{ admin.name }}"
    mode: 0600
  tags: [ always, started, restarted, recreated ]

- ansible.builtin.import_role:
    name: compose_hull
    tasks_from: deploy_docker
